#!/bin/bash

# Usage: ./pr-commit-msgs.sh START_COMMIT_ID END_COMMIT_ID

if [ $# -ne 2 ]; then
  echo "Usage: $0 START_COMMIT_ID END_COMMIT_ID"
  exit 1
fi

START_COMMIT=$1
END_COMMIT=$2

# Get commit range and format output
git log --no-merges --pretty=format:"%h %an %cd %s%n%b" $START_COMMIT..$END_COMMIT | awk '
BEGIN {
  print "## Combined Commit Messages for PR (" "'$START_COMMIT'" " → " "'$END_COMMIT'" ")\n"
  count = 0
  in_body = 0
}
/^[0-9a-f]{7,} / {
  if (count > 0) print ""
  printf("**Commit %d:** `%s`\n", ++count, $1)
  printf("- **Subject:** %s\n", substr($0, index($0,$2)))
  in_body = 0
  next
}
{
  if (NF == 0) next
  if (!in_body) {
    print "- **Details:**"
    in_body = 1
  }
  printf("  %s\n", $0)
}
END {
  print "\n_Generated by PR commit message aggregator_"
}'