[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { workspace = true }
sha3 = "0.10.8"
log = "0.4.20"
rustc-hex = "2.1.0"
dotenvy = "0.15.7"
jsonrpsee-types = "0.21.0"
ethereum-types = "0.14.1"
tiny-keccak = "2.0.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
secp256k1 = { version = "0.28.2", no-default = true, features = ["recovery"] }
ethereum = { version = "0.15.0", default-features = false, features = [
    "with-serde",
] }
ethabi = "18.0.0"
rlp = "0.5.2"
serde_repr = "0.1.18"


[lints]
workspace = true
