[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
num-traits = "0.2.15"
anyhow = { workspace = true }
chrono = "0.4.27"
scylla = "0.11.1"
hex = { workspace = true }
log = "0.4.18"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
bincode = { workspace = true }

primitives = { package = 'primitives', path = '../primitives', default-features = false }
primitive-types = { version = "0.12", default-features = false }
system = { package = 'system', path = '../system', default-features = false }
runtime_config = { package = 'runtime_config', path = '../runtime_config', default-features = false }
l1x-rpc = { workspace = true }
bigdecimal = "0.4.2"


[lints]
workspace = true
