[package]
name = "validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
hex = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
tempfile = "3.5.0"
log = "0.4.18"
scylla = "0.11.1"
tokio = { workspace = true }
num-traits = "0.2.15"
serde = { version = "1.0.163", features = ["derive"] }
serde_bytes = "0.11.9"
secp256k1 = { version = "0.28.2", features = [
    "global-context",
    "rand-std",
] }
serde_json = "1"

account = { package = 'account', path = '../account', default-features = false }
primitives = { package = 'primitives', path = '../primitives', default-features = false }
system = { package = 'system', path = '../system', default-features = false }
cluster = { package = 'cluster', path = '../cluster', default-features = false }
db = { package = 'db', path = '../db', default-features = false }
block_proposer = { package = 'block_proposer', path = '../block_proposer', default-features = false }
node_info = { package = 'node_info', path = '../node_info', default-features = false }
block = { package = 'block', path = '../block', default-features = false }
block-proposer = { package = 'block_proposer', path = '../block_proposer', default-features = false }
contract = { package = 'contract', path = '../contract', default-features = false }
contract_instance = { package = 'contract_instance', path = '../contract_instance', default-features = false }
l1x-vrf = { package = 'l1x-vrf', path = '../l1x-vrf', default-features = false }
staking = { package = 'staking', path = '../staking', default-features = false }
util = { package = 'util', path = '../util', default-features = false }
mint = { package = 'mint', path = '../mint', default-features = false }
validator = { package = 'validator', path = '../validator', default-features = false }
compile_time_config = { package = 'compile_time_config', path = '../compile_time_config'}
execute = { package = 'execute', path = '../execute', default-features = false }

rbpf = { package = 'rbpf', path = '../vm/l1x-rbpf/' }
l1x-ebpf-runtime = { package = 'l1x-ebpf-runtime', path = '../vm/l1x-ebpf-runtime/' }
runtime_config = { package = 'runtime_config', path = '../runtime_config' }

serial_test = "3.0.0"
async-trait = { workspace = true }


[lints]
workspace = true
