[package]
name = "runtime_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
l1x-sdk = { workspace = true }
borsh = { workspace = true }
serde_json = "1.0.96"
primitives = { package = 'primitives', path = '../primitives', default-features = false }
toml = "0.8.1"
serde = { version = "1.0.163", features = ["derive"] }
once_cell = "1.20"
macropol = "0.1.3"
l1x-rpc = { workspace = true }

[lints]
workspace = true
