[package]
name = "relayer"
version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.8", features = ["ws", "rustls"] }
tokio = { workspace = true }
pretty_env_logger = "0.5.0"
log = "0.4.18"


[lints]
workspace = true
