[package]
name = "system_contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { package = 'primitives', path = '../primitives', default-features = false }
compile_time_config = { package = 'compile_time_config', path = '../compile_time_config' }
hex = { workspace = true }
hex-literal = { workspace = true }
base64 = { workspace = true }
l1x-sdk = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
devnet = ["compile_time_config/devnet"]
testnet= ["compile_time_config/testnet"]
mainnet = ["compile_time_config/mainnet"]

[lints]
workspace = true
