[package]
name = "staking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_bytes = "0.11.9"
hex = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
tempfile = "3.5.0"
scylla = "0.11.1"
tokio = { workspace = true }
num-traits = "0.2.15"
log = "0.4.14"
rocksdb = "0.21.0"

# L1X Dependencies
db = { package = 'db', path = '../db', default-features = false }
primitives = { package = 'primitives', path = '../primitives', default-features = false }
system = { package = 'system', path = '../system', default-features = false }
account = { package = 'account', path = '../account', default-features = false }
l1x-vrf = { package = 'l1x-vrf', path = '../l1x-vrf', default-features = false }
db_traits = { package = 'db_traits', path = '../db_traits', default-features = false }
async-trait = { workspace = true }
diesel = { version = "2.1.3", features = [
    "postgres",
    "chrono",
    "numeric",
    "r2d2",
] }
bigdecimal = "0.4.2"
util = { package = 'util', path = '../util', default-features = false }
[dev-dependencies]
common = { package = 'common', path = '../common', default-features = false }


[lints]
workspace = true
